### ISSUE TITLE
Plugins' onEnd are never called

### ISSUE THREAD

**Issue by sdockray** [sdockray/scavenge#2]
```
o = whatsHere(o, transformedInstructions)
o.then((context, data, next, done) => {
        queue.add(...)
})
.done(() => {
```      

Execution never reaches the **.done()** above so the plugins never have a chance to do their onEnd stuff. Running _oz_ with the new jsonManifest plugin demonstrates it because you expect to see some logging, or the manifest spit out at the end.

**Comment by e-e-e** [comment]
just resolved this in this commit https://github.com/sdockray/scavenge/commit/9d911de26e9f0b79879821f238904724040c2b93
